import React from 'react';
import {
  X,
  ExternalLink,
  ShieldCheck,
  Clock,
  Hash,
  Database,
  FileCheck2,
  AlertCircle,
  HelpCircle,
  Layers,
} from 'lucide-react';
import type { Opportunity, RetrievedEvidenceItem } from '@/data/agents';

interface Props {
  opportunity: Opportunity | null;
  isOpen: boolean;
  onClose: () => void;
}

export const EvidenceModal: React.FC<Props> = ({ opportunity, isOpen, onClose }) => {
  if (!isOpen || !opportunity) return null;

  const prov = opportunity.provenance || 'SIMULATED_DEMO';
  const isVerified = Boolean(opportunity.is_verified);
  const evidenceList: RetrievedEvidenceItem[] = opportunity.evidence || [];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-4 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-slate-200 bg-white p-6 shadow-2xl">
        {/* Close Button */}
        <button
          type="button"
          onClick={onClose}
          aria-label="Close evidence inspection"
          className="absolute right-4 top-4 rounded-xl p-1.5 text-slate-400 hover:bg-slate-100 hover:text-slate-600 transition"
        >
          <X className="h-5 w-5" />
        </button>

        {/* Header */}
        <div className="flex items-start gap-3">
          <div
            className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${
              isVerified
                ? 'bg-emerald-50 text-emerald-600'
                : prov === 'CACHED_SOURCE'
                ? 'bg-amber-50 text-amber-600'
                : 'bg-indigo-50 text-indigo-600'
            }`}
          >
            {isVerified ? <ShieldCheck className="h-5 w-5" /> : <Layers className="h-5 w-5" />}
          </div>
          <div className="min-w-0 flex-1 pr-6">
            <div className="flex flex-wrap items-center gap-2">
              <span className="font-mono text-xs font-semibold uppercase tracking-wider text-slate-400">
                Evidence Audit Trail
              </span>
              <span
                className={`rounded-full px-2.5 py-0.5 text-[10px] font-bold tracking-wide uppercase ${
                  prov === 'LIVE_SOURCE'
                    ? 'border border-emerald-200 bg-emerald-50 text-emerald-700'
                    : prov === 'CACHED_SOURCE'
                    ? 'border border-amber-200 bg-amber-50 text-amber-700'
                    : prov === 'USER_SUPPLIED'
                    ? 'border border-blue-200 bg-blue-50 text-blue-700'
                    : prov === 'MODEL_INFERENCE'
                    ? 'border border-purple-200 bg-purple-50 text-purple-700'
                    : 'border border-slate-200 bg-slate-100 text-slate-600'
                }`}
              >
                {prov.replace('_', ' ')}
              </span>
              {isVerified && (
                <span className="inline-flex items-center gap-1 rounded-full border border-emerald-300 bg-emerald-100 px-2 py-0.5 text-[10px] font-bold text-emerald-800">
                  <FileCheck2 className="h-3 w-3" /> VERIFIED RECEIPT
                </span>
              )}
            </div>
            <h3 className="mt-1.5 text-lg font-bold text-slate-900">{opportunity.title}</h3>
          </div>
        </div>

        {/* Inference vs Grounding Notes */}
        <div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4">
          <div className="flex items-center gap-1.5 text-xs font-semibold text-slate-700">
            <HelpCircle className="h-4 w-4 text-slate-500" />
            <span>Grounded Source Claim Rules</span>
          </div>
          <p className="mt-1 text-xs leading-relaxed text-slate-600">
            {opportunity.inference_notes ||
              (isVerified
                ? 'This opportunity was directly retrieved from external APIs and persisted in the audit ledger before model reasoning.'
                : 'This opportunity was generated by model inference and contextual reasoning without an active live connector.')}
          </p>
        </div>

        {/* Primary Evidence Items */}
        <div className="mt-6 space-y-4">
          <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">
            Linked Retrieved Evidence ({evidenceList.length > 0 ? evidenceList.length : '0 records'})
          </h4>

          {evidenceList.length === 0 ? (
            <div className="rounded-xl border border-dashed border-slate-200 p-5 text-center text-xs text-slate-500">
              <AlertCircle className="mx-auto mb-1.5 h-5 w-5 text-slate-400" />
              No external API source was directly attached for this finding. The model synthesized this recommendation using validated domain benchmarks.
            </div>
          ) : (
            evidenceList.map((ev, idx) => (
              <div
                key={ev.id || idx}
                className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm transition hover:border-slate-300"
              >
                <div className="flex flex-wrap items-start justify-between gap-2">
                  <div>
                    <span className="font-mono text-[10px] font-semibold uppercase text-indigo-600">
                      ID: {ev.id}
                    </span>
                    <h5 className="text-sm font-semibold text-slate-800">{ev.title || ev.source_name}</h5>
                  </div>
                  {ev.quality_score != null && (
                    <span className="rounded bg-slate-100 px-2 py-0.5 font-mono text-[11px] font-medium text-slate-700">
                      Quality: {Math.round(ev.quality_score * 100)}%
                    </span>
                  )}
                </div>

                {ev.excerpt && (
                  <div className="mt-3 rounded-lg border border-slate-100 bg-slate-50 p-3">
                    <div className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                      Retrieved Excerpt
                    </div>
                    <p className="mt-1 font-mono text-xs leading-relaxed text-slate-700">
                      &ldquo;{ev.excerpt}&rdquo;
                    </p>
                  </div>
                )}

                <div className="mt-3 grid grid-cols-2 gap-2 text-[11px] text-slate-500 sm:grid-cols-4">
                  <div className="flex items-center gap-1">
                    <Database className="h-3.5 w-3.5 text-slate-400" />
                    <span>Provider: {ev.provider_id || ev.source_name}</span>
                  </div>
                  <div className="flex items-center gap-1">
                    <Clock className="h-3.5 w-3.5 text-slate-400" />
                    <span>
                      {ev.retrieved_at ? new Date(ev.retrieved_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : 'Recent'}
                    </span>
                  </div>
                  {ev.content_hash && (
                    <div className="flex items-center gap-1" title={ev.content_hash}>
                      <Hash className="h-3.5 w-3.5 text-slate-400" />
                      <span className="font-mono truncate">SHA: {ev.content_hash.slice(0, 8)}...</span>
                    </div>
                  )}
                  {ev.http_status && (
                    <div className="flex items-center gap-1">
                      <span className="inline-block h-2 w-2 rounded-full bg-emerald-500" />
                      <span>HTTP {ev.http_status} OK</span>
                    </div>
                  )}
                </div>

                {ev.source_url && (
                  <div className="mt-3 pt-2 border-t border-slate-100">
                    <a
                      href={ev.source_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-1.5 text-xs font-semibold text-indigo-600 hover:text-indigo-800"
                    >
                      Verify original source URL <ExternalLink className="h-3 w-3" />
                    </a>
                  </div>
                )}
              </div>
            ))
          )}
        </div>

        {/* Footer */}
        <div className="mt-6 flex justify-end border-t border-slate-100 pt-4">
          <button
            type="button"
            onClick={onClose}
            className="rounded-xl border border-slate-200 bg-slate-100 px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-200 transition"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
